-- ==============================================================================
-- SCRIPT DE INICIALIZACIÓN Y CONFIGURACIÓN COMPLETA DE SUPABASE
-- PLATAFORMA "ME VARIEDADES" — BASE DE DATOS Y STORAGE
-- ==============================================================================

-- 1. EXTENSIONES NECESARIAS
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ==============================================================================
-- 2. TABLAS PRINCIPALES DEL SISTEMA
-- ==============================================================================

-- TABLA: clientes
CREATE TABLE IF NOT EXISTS public.clientes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_completo TEXT NOT NULL,
    telefono TEXT NOT NULL,
    fecha_nacimiento DATE,
    dia_cumpleanos INTEGER,
    mes_cumpleanos INTEGER,
    estado_cuenta TEXT DEFAULT 'Sin deudas activas' CHECK (estado_cuenta IN ('Sin deudas activas', 'Con saldo pendiente', 'Préstamo activo', 'al_dia', 'con_saldo', 'atrasado', 'pendiente')),
    pedidos_activos INTEGER DEFAULT 0,
    saldo_pendiente NUMERIC(12, 2) DEFAULT 0,
    prestamos_abiertos INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- TABLA: productos
CREATE TABLE IF NOT EXISTS public.productos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    tipo TEXT NOT NULL,
    genero TEXT,
    costo NUMERIC(12, 2) NOT NULL DEFAULT 0,
    stock INTEGER NOT NULL DEFAULT 0 CHECK (stock >= 0),
    imagen_url TEXT,
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- TABLA: pedidos
CREATE TABLE IF NOT EXISTS public.pedidos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT NOT NULL REFERENCES public.clientes(id) ON DELETE CASCADE,
    producto_id BIGINT NOT NULL REFERENCES public.productos(id) ON DELETE RESTRICT,
    cantidad INTEGER NOT NULL DEFAULT 1 CHECK (cantidad > 0),
    total NUMERIC(12, 2) NOT NULL DEFAULT 0,
    estado TEXT DEFAULT 'Activo' CHECK (estado IN ('Activo', 'Entregado', 'Cancelado')),
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- TABLA: pagos (Cuentas por Cobrar y Acuerdos de Pago)
CREATE TABLE IF NOT EXISTS public.pagos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT NOT NULL REFERENCES public.clientes(id) ON DELETE CASCADE,
    concepto TEXT NOT NULL,
    pedido_asociado TEXT,
    monto_total NUMERIC(12, 2) NOT NULL DEFAULT 0,
    monto_pagado NUMERIC(12, 2) NOT NULL DEFAULT 0,
    saldo_pendiente NUMERIC(12, 2) NOT NULL DEFAULT 0,
    fecha_acordada DATE,
    estado TEXT DEFAULT 'pendiente' CHECK (estado IN ('pagado', 'pendiente', 'proximo', 'vencido')),
    abonos JSONB DEFAULT '[]'::jsonb,
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- TABLA: cobros (Historial de Recaudaciones / Ingresos Directos)
CREATE TABLE IF NOT EXISTS public.cobros (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT NOT NULL REFERENCES public.clientes(id) ON DELETE CASCADE,
    monto_cobrado NUMERIC(12, 2) NOT NULL DEFAULT 0 CHECK (monto_cobrado > 0),
    fecha_cobro DATE DEFAULT CURRENT_DATE NOT NULL,
    metodo_pago TEXT DEFAULT 'Efectivo',
    numero_recibo TEXT,
    concepto TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- TABLA: prestamos
CREATE TABLE IF NOT EXISTS public.prestamos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT REFERENCES public.clientes(id) ON DELETE CASCADE,
    nombre_tercero TEXT,
    telefono TEXT,
    monto_capital NUMERIC(12, 2) NOT NULL DEFAULT 0 CHECK (monto_capital > 0),
    tasa_interes NUMERIC(5, 2) NOT NULL DEFAULT 0 CHECK (tasa_interes >= 0),
    total_devolver NUMERIC(12, 2) NOT NULL DEFAULT 0,
    saldo_pendiente NUMERIC(12, 2) NOT NULL DEFAULT 0,
    fecha_entrega DATE DEFAULT CURRENT_DATE NOT NULL,
    fecha_limite DATE NOT NULL,
    estado TEXT DEFAULT 'al_dia' CHECK (estado IN ('al_dia', 'proximo', 'atrasado', 'liquidado')),
    abonos JSONB DEFAULT '[]'::jsonb,
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- TABLA: facturas_comprobantes
CREATE TABLE IF NOT EXISTS public.facturas_comprobantes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT NOT NULL REFERENCES public.clientes(id) ON DELETE CASCADE,
    tipo_categoria TEXT NOT NULL CHECK (tipo_categoria IN ('pedidos', 'pagos', 'cobros', 'prestamos')),
    identificador_ref TEXT,
    archivo_url TEXT NOT NULL,
    archivo_nombre TEXT,
    archivo_tipo TEXT DEFAULT 'image',
    archivo_size BIGINT DEFAULT 0,
    monto NUMERIC(12, 2),
    notas TEXT,
    fecha_emision DATE DEFAULT CURRENT_DATE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- ==============================================================================
-- 3. ÍNDICES DE ALTO RENDIMIENTO
-- ==============================================================================
CREATE INDEX IF NOT EXISTS idx_clientes_nombre ON public.clientes(nombre_completo);
CREATE INDEX IF NOT EXISTS idx_clientes_telefono ON public.clientes(telefono);
CREATE INDEX IF NOT EXISTS idx_productos_nombre ON public.productos(nombre);
CREATE INDEX IF NOT EXISTS idx_pedidos_cliente ON public.pedidos(cliente_id);
CREATE INDEX IF NOT EXISTS idx_pedidos_producto ON public.pedidos(producto_id);
CREATE INDEX IF NOT EXISTS idx_pagos_cliente ON public.pagos(cliente_id);
CREATE INDEX IF NOT EXISTS idx_cobros_cliente ON public.cobros(cliente_id);
CREATE INDEX IF NOT EXISTS idx_prestamos_cliente ON public.prestamos(cliente_id);
CREATE INDEX IF NOT EXISTS idx_facturas_cliente ON public.facturas_comprobantes(cliente_id);

-- ==============================================================================
-- 4. TRIGGER: DESCONTAR STOCK AUTOMÁTICO AL REGISTRAR PEDIDO
-- ==============================================================================
CREATE OR REPLACE FUNCTION public.fn_descontar_stock_pedido()
RETURNS TRIGGER AS $$
DECLARE
    v_stock_actual INTEGER;
BEGIN
    -- Obtener el stock actual del producto
    SELECT stock INTO v_stock_actual FROM public.productos WHERE id = NEW.producto_id;
    
    -- Validar que haya stock suficiente
    IF v_stock_actual < NEW.cantidad THEN
        RAISE EXCEPTION 'Stock insuficiente para el producto ID %. Stock actual: %, solicitado: %', NEW.producto_id, v_stock_actual, NEW.cantidad;
    END IF;

    -- Descontar el stock en la tabla de productos
    UPDATE public.productos
    SET stock = stock - NEW.cantidad
    WHERE id = NEW.producto_id;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS tr_descontar_stock_pedido ON public.pedidos;
CREATE TRIGGER tr_descontar_stock_pedido
AFTER INSERT ON public.pedidos
FOR EACH ROW
EXECUTE FUNCTION public.fn_descontar_stock_pedido();

-- ==============================================================================
-- 5. CONFIGURACIÓN DE STORAGE BUCKETS (PÚBLICOS)
-- ==============================================================================

-- Inserción de buckets de almacenamiento
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES 
    ('imagenes-productos', 'imagenes-productos', true, 5242880, ARRAY['image/jpeg', 'image/png', 'image/webp', 'image/gif']),
    ('comprobantes-facturas', 'comprobantes-facturas', true, 10485760, ARRAY['image/jpeg', 'image/png', 'image/webp', 'application/pdf'])
ON CONFLICT (id) DO UPDATE 
SET public = true;

-- ==============================================================================
-- 6. POLÍTICAS DE ACCESO (ROW LEVEL SECURITY - RLS)
-- ==============================================================================

-- Deshabilitar RLS en todas las tablas para permitir lectura/escritura inmediata
ALTER TABLE public.clientes DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.productos DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.pedidos DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.pagos DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.cobros DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.prestamos DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.facturas_comprobantes DISABLE ROW LEVEL SECURITY;

-- Políticas para Storage (Subida y Descarga pública)
DROP POLICY IF EXISTS "Lectura publica de storage" ON storage.objects;
CREATE POLICY "Lectura publica de storage" ON storage.objects
FOR SELECT TO public USING (bucket_id IN ('imagenes-productos', 'comprobantes-facturas'));

DROP POLICY IF EXISTS "Subida publica de storage" ON storage.objects;
CREATE POLICY "Subida publica de storage" ON storage.objects
FOR INSERT TO public WITH CHECK (bucket_id IN ('imagenes-productos', 'comprobantes-facturas'));

DROP POLICY IF EXISTS "Actualizacion publica de storage" ON storage.objects;
CREATE POLICY "Actualizacion publica de storage" ON storage.objects
FOR UPDATE TO public USING (bucket_id IN ('imagenes-productos', 'comprobantes-facturas'));

DROP POLICY IF EXISTS "Eliminacion publica de storage" ON storage.objects;
CREATE POLICY "Eliminacion publica de storage" ON storage.objects
FOR DELETE TO public USING (bucket_id IN ('imagenes-productos', 'comprobantes-facturas'));
